### ISSUE TITLE
Display on iPad & iPhone

### ISSUE THREAD

**Issue by charlotteyork** [mazikwyry/gpp#12]
The website doesn't seem to display properly on an iPad - on the iPad you can't see anything except the Menu screen. On the iPhone, the homepage displays but then you have to scroll down a very long time and there is nothing, just the green background. Please could you look into this? Two screenshots below

![ipad_longscroll](https://cloud.githubusercontent.com/assets/10221350/5485148/d742b1c0-868e-11e4-8eb3-7f767367ec53.PNG)

![gponipad](https://cloud.githubusercontent.com/assets/10221350/5485129/71706d24-868e-11e4-800a-488a631dd6e8.PNG)

**Comment by mazikwyry** [comment]
Sorry it taken soo long time to fix it but we have to find way to simulate you device. But it's fixed now. Check it out.

**Comment by charlotteyork** [comment]
Great thanks, will check it out!
