### ISSUE TITLE
New testimonial

### ISSUE THREAD

**Issue by charlotteyork** [mazikwyry/gpp#18]
Hi, I'm trying to add a new testimonial to GPP for Jonathan Hall. When I preview it, I only see the name of the person writing the testimonial so I think I might be doing something wrong? Do you mind checking please so I don't publish the wrong thing?! :)

Thanks!

![image](https://cloud.githubusercontent.com/assets/10221350/5529523/37f18e7a-8a0d-11e4-8b19-fa14f88d7cab.png)

**Comment by charlotteyork** [comment]
Hi Adam, Happy New Year!

I managed to upload Jonathan's image about 30 minutes ago but now when I try to add a new image it won't let me.Please see error message below:

![image](https://cloud.githubusercontent.com/assets/10221350/5662118/81e52506-972c-11e4-93e8-d2610c28f615.png)

**Comment by mazikwyry** [comment]
It's a permissions problem again. Please contact Carrenza and send them this image. This error should tell them what to do.
